### ISSUE TITLE
Unknown signal name: draw

### ISSUE THREAD

**Issue by CyrilleGUIEU** [mirefek/geo_logic#3]
Hello,
thanks for this work, I'd like to use it in a (experimental) mathematic course.
I think I missed something in the installation but I don't understand what. Could you help me ?
> Cyrille@Boulot-CG MINGW64 ~
> $ python3 euclidea.py 01_alpha/01_T1_line.py
> Enabled tools:
>   line (l)
> Tool: line
> Traceback (most recent call last):
>   File "C:/msys64/home/Cyrille/euclidea.py", line 205, in <module>
>     win = Drawing(env, win_size)
>           ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:/msys64/home/Cyrille/euclidea.py", line 22, in __init__
>     self.darea.connect("draw", self.on_draw)
> TypeError: <Gtk.DrawingArea object at 0x000001a449a86b00 (GtkDrawingArea at 0x000001a446973540)>: un
> known signal name: draw

**Comment by mirefek** [comment]
Maybe, I forgot to put `pycairo` to the dependencies... Installing it could help... Does this example work for you? https://web.archive.org/web/20230131232544/https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html
By the way, the error you are showing belongs to `py_euclidea` but it doesn't really matter -- they both use the same library for drawing.

**Comment by mirefek** [comment]
Did you get any progress, @CyrilleGUIEU ? I don't use Windows, so it is hard for me to help / test this directly. If there would be a solution, I would be happy to put it to the README.

**Comment by CyrilleGUIEU** [comment]
Thanks for your help but unfortunatly the problem is not solved. The same error appears after Cairo installation by 
>pacman -S mingw-w64-x86_64-python-cairo
An other idea ?

**Comment by mirefek** [comment]
The other issue could be that you are in fact using Gtk4, and it doesn't manage to understand Gtk3 API.

1. Does the `hello.py` example [here](https://pygobject.readthedocs.io/en/latest/getting_started.html) works? And does it also work if you replace "4.0" with "3.0"?
2. Does the [example](https://web.archive.org/web/20230131232544/https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html) I mentioned earlier works? And does the analogous [example](https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html) using Gtk4?

Let me know about each of these four examples if they work or not.

If it turns out that the issue is indeed the Gtk3 / Gtk4 incompatibility, you would probably need to find all the places which require Gtk4 in the code, and fix that (for example this `set_draw_func` instead of `connect("draw")` like in the Cairo Integration example). But I don't have Gtk4, so it would be better if you could do it yourself. I could try to help when you would encounter other error messages due to this incompatibility.

**Comment by CyrilleGUIEU** [comment]
I just install Gtk3 instead of Gtk4 and it works !
Here the [tuto]([https://www.gtk.org/docs/installations/windows])
Thank you very much for your work and your help !
